# Generated by Django 3.2.8 on 2022-10-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('TT_NO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('JOB', models.CharField(max_length=1)),
                ('Date', models.DateField()),
                ('IS_MI', models.IntegerField()),
                ('cyc_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
